name: github-actions
on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev', 'main'
  create:
jobs:
  first-job:
    name: Greetings
    runs-on: macos-12
    steps:
      - name: Print a greeting
        env:
          MY_VAR_1: Hi there! My name is
          MY_VAR_2: and i'm trying to figure out ci
          FIRST_NAME: Alice
        run: |
          echo $MY_VAR $FIRST_NAME $MY_VAR_2.
  build:
    name: Gradle Build
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'coretto-17'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build
